services:
  - type: web
    name: mobile-provider-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/mobileprovider-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:jdbc:postgresql://dpg-d00ho7ili9vc739u99gg-a.frankfurt-postgres.render.com:5432/mobile_provider_db
      - key: SPRING_DATASOURCE_USERNAME
        value: gizoskos
      - key: SPRING_DATASOURCE_PASSWORD
        value: YLzPiFaxyQXekUQvZQYAcvXZV2so0jbJ
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update